### ISSUE TITLE
Advanced multiple targets / Nextjs issue >= 2.2.0

### ISSUE THREAD

**Issue by Axelr** [bitworking/react-gsap#18]
Hello, I can't get this example to work : https://bitworking.github.io/react-gsap/src-components-timeline#advanced-multiple-targets

I got the following error message `targets.set is not a function`

Here is my component :
``` jsx
import React, { forwardRef } from 'react'

const LogoGimik = forwardRef((props, targets) => (
    <div className="logo-gimik" ref={div => targets.set('logoWrapper', div)}>
        <div className="corner corner-1" ref={div => targets.set('corner1', div)} />
        <div className="circle" ref={div => targets.set('circle', div)} />
        <div className="corner corner-2" ref={div => targets.set('corner2', div)} />
        <div className="line" ref={div => targets.set('line', div)} />
    </div>
))

export default LogoGimik
```
Used here :
``` jsx
<Timeline
    target={<LogoGimik />}
    totalProgress={progress}
    paused
>
    <Tween
        target="logoWrapper"
        to={{
            css: {
                width: '370px',
                height: '320px',
            },
        }}
    />
</Timeline>
```
What i am trying to do is animate both the parent & his child in a single timeline.

Thanks if you have any advice.

**Comment by bitworking** [comment]
I've tested it and it works. Please make sure you're using version >= 2.2.0 because this feature was introduced with this version.

**Comment by Axelr** [comment]
Thanks, i was not on the good version, but the real point is that i'm with Next.js.

I have this error :
```
Unexpected token {
C:\Users\Aroche\projects\wordpress\structuro\structuro-app\node_modules\gsap\CSSPlugin.js:12
import { gsap, _getProperty, _numExp, _numWithUnitExp, getUnit, _isString, _isUndefined, _renderComplexString, _relExp, _forEachName, _sortPropTweensByPriority, _colorStringFilter, _checkPlugin, _replaceRandom, _plugins, GSCache, PropTween, _config, _ticker, _round, _missingPlugin, _getSetter, _getCache, _setDefaults, _removeLinkedListItem //for the commented-out className feature.
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Aroche\projects\wordpress\structuro\structuro-app\node_modules\react-gsap\dist\react-gsap.cjs.development.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```
I can fix it using a dynamic import

**Comment by bitworking** [comment]
Ok shit, I think I forgot to test the new version with SSR.

I'll have a look and release a new version later.

**Comment by bitworking** [comment]
Ok please test it now with version 2.2.1. SSR and IE11 should work.

Info: I've imported the CSSPlugin because sometimes it seemed that this plugin was removed from the treeshaking. But gsap only exports an ES6 version, so I removed the import for now completely.

**Comment by Axelr** [comment]
Seems fixed for me ! Thank you verry much for the super efficient intervention !
